// src/lib/mockContratos.ts
import { Contrato, SituacaoContrato } from "@/types/api";

export const mockContratos: Contrato[] = [
  {
    id: 1,
    clienteId: 1,
    cliente: {
      id: 1,
      tipoPessoa: "Fisica",
      pessoaFisicaId: 1,
      pessoaFisica: {
        id: 1,
        nome: "João Silva Santos",
        email: "joao.silva@email.com",
        cpf: "123.456.789-00",
        telefone1: "(11) 98765-4321",
        telefone2: "",
        sexo: "M",
        dataNascimento: "1985-05-15",
        estadoCivil: "Casado",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 1,
        endereco: {
          id: 1,
          logradouro: "Rua das Flores",
          numero: "123",
          bairro: "Centro",
          cidade: "São Paulo",
          cep: "01000-000",
          complemento: "Apto 45",
        },
        dataCadastro: "2024-01-15T10:00:00",
      },
      filialId: 1,
      filial: "São Paulo - SP",
      status: "Ativo",
      observacoes: "Cliente preferencial",
      valorContrato: 50000,
      dataCadastro: "2024-01-15T10:00:00",
      ativo: true,
    },
    consultorId: 1,
    consultor: {
      id: 1,
      pessoaFisicaId: 2,
      pessoaFisica: {
        id: 2,
        nome: "Dra. Maria Oliveira",
        email: "maria.oliveira@arrighi.com",
        cpf: "987.654.321-00",
        telefone1: "(11) 91234-5678",
        telefone2: "",
        sexo: "F",
        dataNascimento: "1980-08-20",
        estadoCivil: "Solteiro",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 2,
        endereco: {
          id: 2,
          logradouro: "Av. Paulista",
          numero: "1000",
          bairro: "Bela Vista",
          cidade: "São Paulo",
          cep: "01310-100",
          complemento: "Sala 1501",
        },
        dataCadastro: "2023-06-01T09:00:00",
      },
      filial: "São Paulo - SP",
      oab: "SP123456",
      dataCadastro: "2023-06-01T09:00:00",
      ativo: true,
    },
    situacao: "Negociacao" as SituacaoContrato,
    dataUltimoContato: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    dataProximoContato: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    valorDevido: 50000,
    valorNegociado: 45000,
    observacoes: "Cliente interessado em fechar até o final do mês",
    dataCadastro: "2024-01-15T10:00:00",
    dataAtualizacao: new Date().toISOString(),
    ativo: true,
  },
  {
    id: 2,
    clienteId: 2,
    cliente: {
      id: 2,
      tipoPessoa: "Juridica",
      pessoaJuridicaId: 1,
      pessoaJuridica: {
        id: 1,
        razaoSocial: "Tech Solutions Ltda",
        nomeFantasia: "TechSol",
        cnpj: "12.345.678/0001-90",
        email: "contato@techsol.com",
        telefone1: "(11) 3456-7890",
        telefone2: "(11) 3456-7891",
        responsavelTecnicoId: 3,
        responsavelTecnico: {
          id: 3,
          nome: "Carlos Eduardo",
          email: "carlos@techsol.com",
          cpf: "456.789.123-00",
          telefone1: "(11) 94567-8901",
          telefone2: "",
          sexo: "M",
          dataNascimento: "1990-03-10",
          estadoCivil: "Casado",
          codinome: "",
          rg: "",
          cnh: "",
          enderecoId: 3,
          endereco: {
            id: 3,
            logradouro: "Rua Augusta",
            numero: "2000",
            bairro: "Jardins",
            cidade: "São Paulo",
            cep: "01412-100",
            complemento: "",
          },
          dataCadastro: "2024-02-01T14:00:00",
        },
        enderecoId: 3,
        endereco: {
          id: 3,
          logradouro: "Rua Augusta",
          numero: "2000",
          bairro: "Jardins",
          cidade: "São Paulo",
          cep: "01412-100",
          complemento: "Prédio A",
        },
        dataCadastro: "2024-02-01T14:00:00",
      },
      filialId: 2,
      filial: "Rio de Janeiro - RJ",
      status: "Prospecto",
      observacoes: "Empresa em expansão",
      valorContrato: 120000,
      dataCadastro: "2024-02-01T14:00:00",
      ativo: true,
    },
    consultorId: 2,
    consultor: {
      id: 2,
      pessoaFisicaId: 4,
      pessoaFisica: {
        id: 4,
        nome: "Dr. Pedro Almeida",
        email: "pedro.almeida@arrighi.com",
        cpf: "321.654.987-00",
        telefone1: "(21) 98765-1234",
        telefone2: "",
        sexo: "M",
        dataNascimento: "1975-12-05",
        estadoCivil: "Divorciado",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 4,
        endereco: {
          id: 4,
          logradouro: "Av. Atlântica",
          numero: "500",
          bairro: "Copacabana",
          cidade: "Rio de Janeiro",
          cep: "22021-000",
          complemento: "Cobertura",
        },
        dataCadastro: "2023-08-15T11:00:00",
      },
      filial: "Rio de Janeiro - RJ",
      oab: "RJ789012",
      dataCadastro: "2023-08-15T11:00:00",
      ativo: true,
    },
    situacao: "Prospecto" as SituacaoContrato,
    dataUltimoContato: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    dataProximoContato: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    valorDevido: 120000,
    valorNegociado: undefined,
    observacoes: "Aguardando aprovação da diretoria",
    dataCadastro: "2024-02-01T14:00:00",
    dataAtualizacao: undefined,
    ativo: true,
  },
  {
    id: 3,
    clienteId: 3,
    cliente: {
      id: 3,
      tipoPessoa: "Fisica",
      pessoaFisicaId: 5,
      pessoaFisica: {
        id: 5,
        nome: "Ana Paula Ferreira",
        email: "ana.ferreira@gmail.com",
        cpf: "789.123.456-00",
        telefone1: "(11) 97654-3210",
        telefone2: "",
        sexo: "F",
        dataNascimento: "1992-07-25",
        estadoCivil: "Solteiro",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 5,
        endereco: {
          id: 5,
          logradouro: "Rua Oscar Freire",
          numero: "800",
          bairro: "Pinheiros",
          cidade: "São Paulo",
          cep: "05409-010",
          complemento: "Casa 2",
        },
        dataCadastro: "2024-03-10T16:30:00",
      },
      filialId: 1,
      filial: "São Paulo - SP",
      status: "Ativo",
      observacoes: "Cliente novo",
      valorContrato: 25000,
      dataCadastro: "2024-03-10T16:30:00",
      ativo: true,
    },
    consultorId: 1,
    consultor: {
      id: 1,
      pessoaFisicaId: 2,
      pessoaFisica: {
        id: 2,
        nome: "Dra. Maria Oliveira",
        email: "maria.oliveira@arrighi.com",
        cpf: "987.654.321-00",
        telefone1: "(11) 91234-5678",
        telefone2: "",
        sexo: "F",
        dataNascimento: "1980-08-20",
        estadoCivil: "Solteiro",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 2,
        endereco: {
          id: 2,
          logradouro: "Av. Paulista",
          numero: "1000",
          bairro: "Bela Vista",
          cidade: "São Paulo",
          cep: "01310-100",
          complemento: "Sala 1501",
        },
        dataCadastro: "2023-06-01T09:00:00",
      },
      filial: "São Paulo - SP",
      oab: "SP123456",
      dataCadastro: "2023-06-01T09:00:00",
      ativo: true,
    },
    situacao: "Fechado" as SituacaoContrato,
    dataUltimoContato: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    dataProximoContato: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    valorDevido: 25000,
    valorNegociado: 25000,
    observacoes: "Contrato fechado com sucesso",
    dataCadastro: "2024-03-10T16:30:00",
    dataAtualizacao: new Date().toISOString(),
    ativo: true,
  },
  {
    id: 4,
    clienteId: 4,
    cliente: {
      id: 4,
      tipoPessoa: "Fisica",
      pessoaFisicaId: 6,
      pessoaFisica: {
        id: 6,
        nome: "Roberto Costa",
        email: "roberto.costa@hotmail.com",
        cpf: "654.321.987-00",
        telefone1: "(11) 96543-2109",
        telefone2: "",
        sexo: "M",
        dataNascimento: "1988-11-30",
        estadoCivil: "Casado",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 6,
        endereco: {
          id: 6,
          logradouro: "Alameda Santos",
          numero: "1500",
          bairro: "Cerqueira César",
          cidade: "São Paulo",
          cep: "01418-100",
          complemento: "Bloco B",
        },
        dataCadastro: "2024-01-20T09:15:00",
      },
      filialId: 1,
      filial: "São Paulo - SP",
      status: "Inativo",
      observacoes: "Cliente perdido para concorrência",
      valorContrato: 35000,
      dataCadastro: "2024-01-20T09:15:00",
      ativo: false,
    },
    consultorId: 3,
    consultor: {
      id: 3,
      pessoaFisicaId: 7,
      pessoaFisica: {
        id: 7,
        nome: "Dr. Lucas Martins",
        email: "lucas.martins@arrighi.com",
        cpf: "159.753.852-00",
        telefone1: "(11) 95432-1098",
        telefone2: "",
        sexo: "M",
        dataNascimento: "1985-04-18",
        estadoCivil: "Casado",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 7,
        endereco: {
          id: 7,
          logradouro: "Rua Vergueiro",
          numero: "3000",
          bairro: "Vila Mariana",
          cidade: "São Paulo",
          cep: "04101-300",
          complemento: "",
        },
        dataCadastro: "2023-09-01T10:00:00",
      },
      filial: "São Paulo - SP",
      oab: "SP456789",
      dataCadastro: "2023-09-01T10:00:00",
      ativo: true,
    },
    situacao: "Perdido" as SituacaoContrato,
    dataUltimoContato: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    dataProximoContato: "",
    valorDevido: 35000,
    valorNegociado: undefined,
    observacoes: "Cliente optou por outro escritório",
    dataCadastro: "2024-01-20T09:15:00",
    dataAtualizacao: new Date(
      Date.now() - 10 * 24 * 60 * 60 * 1000
    ).toISOString(),
    ativo: false,
  },
  {
    id: 5,
    clienteId: 5,
    cliente: {
      id: 5,
      tipoPessoa: "Juridica",
      pessoaJuridicaId: 2,
      pessoaJuridica: {
        id: 2,
        razaoSocial: "Comércio Digital S.A.",
        nomeFantasia: "DigiStore",
        cnpj: "98.765.432/0001-10",
        email: "contato@digistore.com.br",
        telefone1: "(11) 2345-6789",
        telefone2: "",
        responsavelTecnicoId: 8,
        responsavelTecnico: {
          id: 8,
          nome: "Juliana Mendes",
          email: "juliana@digistore.com.br",
          cpf: "852.963.741-00",
          telefone1: "(11) 93210-9876",
          telefone2: "",
          sexo: "F",
          dataNascimento: "1995-06-12",
          estadoCivil: "Solteiro",
          codinome: "",
          rg: "",
          cnh: "",
          enderecoId: 8,
          endereco: {
            id: 8,
            logradouro: "Av. Faria Lima",
            numero: "3500",
            bairro: "Itaim Bibi",
            cidade: "São Paulo",
            cep: "04538-132",
            complemento: "Torre A",
          },
          dataCadastro: "2024-04-05T13:45:00",
        },
        enderecoId: 8,
        endereco: {
          id: 8,
          logradouro: "Av. Faria Lima",
          numero: "3500",
          bairro: "Itaim Bibi",
          cidade: "São Paulo",
          cep: "04538-132",
          complemento: "Torre A, Andar 15",
        },
        dataCadastro: "2024-04-05T13:45:00",
      },
      filialId: 1,
      filial: "São Paulo - SP",
      status: "Ativo",
      observacoes: "Cliente estratégico",
      valorContrato: 200000,
      dataCadastro: "2024-04-05T13:45:00",
      ativo: true,
    },
    consultorId: 1,
    consultor: {
      id: 1,
      pessoaFisicaId: 2,
      pessoaFisica: {
        id: 2,
        nome: "Dra. Maria Oliveira",
        email: "maria.oliveira@arrighi.com",
        cpf: "987.654.321-00",
        telefone1: "(11) 91234-5678",
        telefone2: "",
        sexo: "F",
        dataNascimento: "1980-08-20",
        estadoCivil: "Solteiro",
        codinome: "",
        rg: "",
        cnh: "",
        enderecoId: 2,
        endereco: {
          id: 2,
          logradouro: "Av. Paulista",
          numero: "1000",
          bairro: "Bela Vista",
          cidade: "São Paulo",
          cep: "01310-100",
          complemento: "Sala 1501",
        },
        dataCadastro: "2023-06-01T09:00:00",
      },
      filial: "São Paulo - SP",
      oab: "SP123456",
      dataCadastro: "2023-06-01T09:00:00",
      ativo: true,
    },
    situacao: "Leed" as SituacaoContrato,
    dataUltimoContato: new Date().toISOString().split("T")[0],
    dataProximoContato: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)
      .toISOString()
      .split("T")[0],
    valorDevido: 200000,
    valorNegociado: undefined,
    observacoes: "Primeiro contato realizado hoje",
    dataCadastro: "2024-04-05T13:45:00",
    dataAtualizacao: undefined,
    ativo: true,
  },
];
